services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    volumes:
      - ${DOCKER_DIR}/termix/data:/app/data
    environment:
      PORT: "8080"
    networks:
      - proxy
    labels:
    #TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.termix.entrypoints=http"
      - "traefik.http.routers.termix.rule=Host(`termix.${DOMAIN}`)" 
      - "traefik.http.middlewares.termix-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.termix.middlewares=termix-https-redirect"
      - "traefik.http.routers.termix-secure.entrypoints=https"
      - "traefik.http.routers.termix-secure.rule=Host(`termix.${DOMAIN}`)" 
      - "traefik.http.routers.termix-secure.tls=true"
      - "traefik.http.routers.termix-secure.service=termix"
      - "traefik.http.services.termix.loadbalancer.server.port=8080" 
      - "traefik.docker.network=proxy"
    #HOMEPAGE
      - homepage.group=${HOMEPAGE_GROUP}
      - homepage.name=termix
      - homepage.icon=termix.png
      - homepage.href=https://termix.${DOMAIN}
    # security_opt:
    #   - no-new-privileges:true

networks:
  proxy:
    external: true